modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "gravels_extended_battles"
version = "${version}"
displayName = "Gravels Extended Battles"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.gravels_extended_battles]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gravels_extended_battles]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gravels_extended_battles]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "gravels_extended_battles.mixins.json"
